services:
  db:
    image: mysql:8.4.7
    container_name: tjma_mysql
    restart: always
    ports: 
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

      - MYSQL_CRAWLER_USER=${MYSQL_CRAWLER_USER}
      - MYSQL_CRAWLER_PASSWORD=${MYSQL_CRAWLER_PASSWORD}

      - MYSQL_WEB_USER=${MYSQL_WEB_USER}
      - MYSQL_WEB_PASSWORD=${MYSQL_WEB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql 
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
  crawler:
    build:
      context: ./services/crawler
      dockerfile: Dockerfile
    container_name: "tjma_crawler"
    ports:
        - "8000:8000"
    env_file:
      - ./services/crawler/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
  web:
    build:
      context: ./services/web_server
      dockerfile: dockerfile
    container_name: "tjma_web"
    ports:
      - "8080:8080"
    env_file:
      - ./services/web_server/.env
    depends_on:
      - db
    environment:
      - DB_HOST=db